source 'https://rubygems.org'

# fixing the ruby version
ruby '2.3.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.0.0'
gem 'rake'

# action mailer for sending the emails
gem 'actionmailer'
# devise for authentication
gem 'devise'
# Use pg as the database for Active Record
gem 'pg'
# for json response https://github.com/rails-api/active_model_serializers
gem "active_model_serializers"
# Use ActiveModel has_secure_password
gem 'bcrypt'


# Use SCSS for stylesheets
gem 'sass-rails'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'


# Use thin as the app server
gem 'thin'

gem 'nokogiri'
gem 'oauth'
gem 'omniauth'
gem 'omniauth-linkedin'



# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

group :development, :test do
# rspec for testing
	gem 'rspec'
	gem "rspec-rails"
	gem "factory_girl_rails", '~>4.2.1'
	gem 'faker', '~> 1.1.2'
 	gem 'better_errors'
end

group :doc do
	# bundle exec rake doc:rails generates the API under doc/api.
	gem 'sdoc', :require => false
end

group :deployment do
# Use Capistrano for deployment
	gem 'capistrano', '~> 3.0.1'
# rails specific capistrano functions
	gem 'capistrano-rails', '~> 1.1.0'
end

group :test do
	gem 'capybara'
	gem 'chromedriver-helper', '~> 0.0.5'
	gem 'cucumber'
	# database_cleaner is not required, but highly recommended
	gem 'database_cleaner'
	gem 'headless'
	gem 'selenium-webdriver'
end
